# Generated by Django 5.1.1 on 2024-09-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stars',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
